version: "3.7"

x-network:
  &network
  networks:
    - investoko_network

services:

  frontend:
    build:
      context: ./frontend
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - "./frontend/app:/app"
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    links:
      - backend
    command: "next dev"
    <<: *network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - "./backend:/app"
    ports:
      - "8000:80"
    <<: *network

  docs:
    build:
      context: ./frontend
      dockerfile: ./docker/docs/Dockerfile
    volumes:
      - "./frontend/app:/app"
    ports:
      - "5000:5000"
    command: "npm run docz:dev"
    <<: *network

networks:
  investoko_network:
    external: true
