version: "3.7"

x-network:
  &network
  networks:
    - investoko_network

services:

  frontend:
    build:
      context: ./frontend
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - "./frontend/app:/app"
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production
      - API_URL=http://backend:1337
    links:
      - backend
    command: "next build && next start"
    <<: *network

  backend:
    image: strapi/strapi
    volumes:
      - ./backend/strapi:/srv/app
    ports:
      - "1337:1337"
    <<: *network

networks:
  investoko_network:
    external: true
